<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <OutputType>WinExe</OutputType>
      <TargetFramework>net10.0-windows</TargetFramework>
      <Nullable>enable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
      <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <Resource Include="Images\congrats.jpg" />
      <Resource Include="Images\ups.jpg" />
      <Resource Include="Images\piedra.jpg" />
      <Resource Include="Images\papel.jpg" />
      <Resource Include="Images\tijeras.jpg" />
      <Resource Include="Images\lagarto.jpg" />
      <Resource Include="Images\fondo.jpg" />
      <Resource Include="Images\spock.webp" />
      <Resource Include="Sounds\piedra.wav" />
      <Resource Include="Sounds\papel.wav" />
      <Resource Include="Sounds\tijera.wav" />
      <Resource Include="Sounds\lagarto.wav" />
      <Resource Include="Sounds\spock.wav" />
    </ItemGroup>


</Project>
